name: Atualização Horária Radar Consuldente

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instalar dependências
      run: |
        pip install requests beautifulsoup4

    - name: Executar Radar
      run: python parser.py

    - name: Salvar no Repositório
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add data.json
        git commit -m "📡 Radar: Notícias Atualizadas" || exit 0
        git push
